### ISSUE TITLE
Remove resource association code from course service & remove pubsub event subscribers and publishers

### ISSUE THREAD

**Issue by myluki2000** [IT-REX-Platform/course_service#50]
## Parent
- IT-REX-Platform/gits_backend#30

## Description
Remove resource association code from course service and remove pub-sub event subscribers and publishers

## Acceptance Criteria
- [ ] code removed
- [ ] pub-sub removed

**Comment by PaulBredl** [comment]
@LG1401 I discussed with @myluki2000 that this has low prio and maybe makes more sense in the last sprint.
Should we move it back to backlog and put something else in?
